app/__init__.py
from flask import Flask
import os
import mysql.connector
from dotenv import load_dotenv
load_dotenv()
app = Flask(__name__)
app.secret_key=os.urandom(24)

conn=mysql.connector.connect(host="remotemysql.com",user=os.getenv("DB_USER"),password=os.getenv("DB_PASS"),database=os.getenv("DB_NAME"))
cursor=conn.cursor()

from app import api
from app.users.auth_routes import users
from app.main.routes import main
from app.maps.map_routes import maps

app.register_blueprint(users)
app.register_blueprint(main)
app.register_blueprint(maps)

from app import matching
from app import ml

app/main/__init__.py
# initializes main as an instance

app/main/routes.py
from flask import Blueprint, render_template, request, redirect, session
from app import cursor
from app import conn
from app.users.auth_routes import email, password

main = Blueprint('main', __name__)

# Main Routes


@main.route('/', methods=['GET', 'POST'])
def index():
    return render_template('home.html')


@main.route('/home')
def home():
    if 'user_id' in session:
        return render_template('home.html')
    else:
        return redirect('/')


@main.route('/form')
def form():
    return render_template('form.html')

# Questionnaire


@main.route('/home', methods=['POST'])
def form_data():
    global result
    if request.method == "POST":
        req = request.form
        movie = req['movie']
        music = req['music']
        sport = req['sport']
        choice = req['choice']
        result = movie+music+sport+choice
        cursor.execute(
            """SELECT * FROM `users`  WHERE `email` LIKE '{}' AND `password` LIKE '{}' """.format(email, password))
        user = cursor.fetchone()
        cursor.execute(
            """UPDATE `users` set results='{}' WHERE email='{}' """.format(result, email))
        conn.commit()
        conn.commit()
        return render_template('home.html')

app/maps/__init__.py
# initializes maps as an instance

app/users/__init__.py
# initializes users as an instance

app/templates/form.html
{% extends "layout.html" %} {% block content %}
<div class="body-main">
  <div class="container" id="bgimage">
    <main class="mb-5">
      <form action="/home" id="survey-form" method="POST">
        <p id="description text-white" style="color: white">
          Help us by answering some questions so that we pool you with like
          minded people :
        </p>
        <div class="form-group">
          <label for="movie" class="fq"
            >What's your favorite movie genre: (Check all that you like)</label
          >
          <label for="movie" class="fq">
            <input type="radio" name="movie" id="" value="a" />Romance
          </label>
          <label for="movie" class="fq">
            <input type="radio" name="movie" id="" value="b" />Thrillers
          </label>
          <label for="movie" class="fq">
            <input type="radio" name="movie" id="" value="c" />Classics
          </label>
          <label for="movie" class="fq">
            <input type="radio" name="movie" id="" value="d" />Comedy
          </label>
          <label for="movie" class="fq">
            <input type="radio" name="movie" id="" value="d" />Science Fiction
          </label>
          <label for="movie" class="fq">
            <input type="radio" name="movie" id="" value="e" />Fantasy
          </label>
        </div>
        <div class="form-group">
          <label for="music" class="fq"
            >What music do you frequently listen to: (Check all that you
            like)</label
          >
          <label for="music" class="fq">
            <input type="radio" name="music" id="" value="a" />Country
          </label>
          <label for="music" class="fq">
            <input type="radio" name="music" id="" value="b" />Pop(current
            artists)
          </label>
          <label for="music" class="fq">
            <input type="radio" name="music" id="" value="c" />Hip Hop
          </label>
          <label for="music" class="fq">
            <input type="radio" name="music" id="" value="d" />Rock and metal
          </label>
          <label for="music" class="fq">
            <input type="radio" name="music" id="" value="e" />Electronic music
          </label>
          <label for="music" class="fq">
            <input type="radio" name="music" id="" value="f" />Jazz, Folk or
            Classical
          </label>
        </div>
        <div class="form-group">
          <label for="sport" class="fq">What's your favorite sport:</label>
          <label for="sport" class="fq">
            <input type="radio" name="sport" id="" value="a" />Football
          </label>
          <label for="sport" class="fq">
            <input type="radio" name="sport" id="" value="b" />NLF
          </label>
          <label for="sport" class="fq">
            <input type="radio" name="sport" id="" value="c" />Hip Hop
          </label>
          <label for="sport" class="fq">
            <input type="radio" name="" id="" value="d" />Basketball
          </label>
          <label for="sport" class="fq">
            <input type="radio" name="sport" id="" value="e" />Tennis
          </label>
          <label for="sport" class="fq">
            <input type="radio" name="sport" id="" value="f" />Cricket
          </label>
          <label for="sport" class="fq">
            <input type="radio" name="sport" id="" value="g" />None of the above
          </label>
        </div>
        <div class="form-group radio-group">
          <label for="" class="fq"
            >Which of the following describes you the best: (Select the best
            one)</label
          >
          <label for="" class="fq">
            <input type="radio" name="choice" value="a" />Supressed emotions,
            hides pain, calm af, impressive sometimes.
          </label>
          <label for="" class="fq">
            <input type="radio" name="choice" value="b" />Funny and childish,
            well tempered, cool af.
          </label>
          <label for="" class="fq">
            <input type="radio" name="choice" value="c" />Short-tempered,
            determained, never give up attitude.
          </label>
          <label for="" class="fq">
            <input type="radio" name="choice" value="d" />Calm, introvert,
            analyses surroundingd before speaking.
          </label>
        </div>
        <div class="form-group btn btn1">
          <div class="inner"></div>
          <button type="submit" id="submit">Submit</button>
        </div>
        <div>
          <ul class="box-area">
            <li class="fas fa-star"></li>
            <li></li>
            <li class="fas fa-star"></li>
            <li></li>
            <li class="fas fa-star"></li>
            <li></li>
            <li class="far fa-snowflake"></li>
            <li></li>
            <li class="far fa-snowflake"></li>
            <li></li>
          </ul>
        </div>
      </form>
    </main>
  </div>
</div>

{% endblock content %}

app/templates/home.html
{% extends "layout.html" %} {% block content %}

<header>
  <nav
    class="fixed-top navbar navbar-dark navbar-expand-md py-0"
    id="mainNavbar"
  >
    <button
      class="navbar-toggler"
      data-toggle="collapse"
      data-target="#navLinks"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navLinks">
      <ul class="navbar-nav">
        <a class="navbar-brand">{{displayname}}</a>
        <li class="nav-item">
          <a href="/login" class="nav-link" style="color: white">LOGIN</a>
        </li>
        <li class="nav-item">
          <a href="/register" class="nav-link" style="color: white">REGISTER</a>
        </li>
        <li class="nav-item">
          <a href="/logout" class="nav-link" style="color: white">LOGOUT</a>
        </li>
        <li class="nav-item">
          <a href="{{url_for('main.form')}}" class="nav-link" style="color: white"
            >FILL FORM</a
          >
        </li>
      </ul>
    </div>
  </nav>

  <div class="textbox-hero p-5">
    <h2 class="text-animation">GROOVE</h2>
    <h1>
      Book a ride.<br />
      We have got a surprise for you.
    </h1>

    <a href="{{ url_for('maps.map1') }}" class="pool-style mt-4">JOIN A POOL</a>
  </div>
</header>

<section class="testimonials" style="background-color: black">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 d-flex justify-content-center">
        <div class="card">
          <div class="card-body text-center">
            <h2 class="number">01</h2>
            <h3 class="number-heading mt-3 pt-4">REGISTER AND LOGIN</h3>
            <p>Register for our services so that we could help you</p>
            <a href="#" class="what-a" style="color: #6c63ff">Read More</a>
          </div>
        </div>
      </div>
      <div class="col-lg-4 d-flex justify-content-center">
        <div class="card">
          <div class="card-body text-center">
            <h2 class="number">02</h2>
            <h3 class="number-heading mt-3 pt-4">REGISTER AND LOGIN</h3>
            <p>Register for our services so that we could help you</p>
            <a href="#" class="what-a" style="color: #6c63ff">Read More</a>
          </div>
        </div>
      </div>
      <div class="col-lg-4 d-flex justify-content-center">
        <div class="card">
          <div class="card-body text-center">
            <h2 class="number">03</h2>
            <h3 class="number-heading mt-3 pt-4">REGISTER AND LOGIN</h3>
            <p>Register for our services so that we could help you</p>
            <a href="#" class="what-a" style="color: #6c63ff">Read More</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="info">
  <div class="row">
    <h2 class="mt-5 mb-1 mx-5">WHAT IS GROOVE</h2>
  </div>
  <div class="col-sm-6">
    <hr class="horizontal" />
  </div>
  <div class="row justify-content-center align-items-center col-sm-6">
    <blockquote class="mx-5 mb-5 line">
      The project aims at destroying this barrier between the people who are
      sharing a ride by grouping up people with shared interests and compatible
      personality types into a pool. We are able to achieve such results with
      the help of techniques like Natural Language Processing (To determine
      someone’s personality type) , Collaborative filtering and decision tree
      classification (For grouping people with similar tastes) .
    </blockquote>
  </div>
</section>
<section class="about">
  <div class="container-fluid px-0">
    <div class="row align-items-center">
      <div class="col-md-6 order-2 order-md-1">
        <img
          src="/static/images/undraw_team_spirit_hrr4.svg"
          class="img-fluid"
          alt=""
        />
      </div>
      <div class="col-md-6 text-center order-1 order-md-2 blurb mb-5 mb-md-0">
        <div class="row justify-content-center mt-3">
          <div class="col-10 col-lg-8">
            <div class="card p-4">
              <div class="about-content">
                <h2>about us</h2>
                <p>
                  We at groovy are trying to create a carpooling service which
                  matches people on the basis of their interests, and
                  personality types.</p>
                   <br>
                  </p>
                  Our company’s vision is to finding effective and viable methods of reducing vehicular emissions and reduce the damage caused on the environment on a daily basis. 
	                We try to help people make their commute which is usually the most strenuous and boring part of the day, interesting by helping them meet new people during travel, while ensuring security and safety of all the commuters
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<script>
  var prevScrollpos = window.pageYOffset;
  window.onscroll = function () {
    var currentScrollPos = window.pageYOffset;
    if (prevScrollpos > currentScrollPos) {
      document.getElementById("mainNavbar").style.top = "0";
    } else {
      document.getElementById("mainNavbar").style.top = "-90px";
    }
    prevScrollpos = currentScrollPos;
  };
</script>

{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <!-- Maps -->
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.js"></script>
    <link
      href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css"
      rel="stylesheet"
    />

    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.0/mapbox-gl-directions.js"></script>
    <link
      rel="stylesheet"
      href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.0/mapbox-gl-directions.css"
      type="text/css"
    />

    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.min.js"></script>

    <!-- Promise polyfill script required to use Mapbox GL Geocoder in IE 11 -->
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
    <link
      rel="stylesheet"
      href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.css"
      type="text/css"
    />

    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>

    <!-- Font awesome -->
    <script
      src="https://kit.fontawesome.com/8a8316e13d.js"
      crossorigin="anonymous"
    ></script>

    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='style.css') }}"
    />

    {% if title %}
    <title>app - {{ title }}</title>
    {% else %}
    <title>app</title>
    {% endif %}
  </head>
  <body>
    {% with messages = get_flashed_messages(with_categories=true) %} {% endwith
    %} {% block content %}{% endblock %}

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <!--Fontawesome-->
    <script
      src="https://kit.fontawesome.com/2b73c9a97e.js"
      crossorigin="anonymous"
    ></script>

    <script type="text/javascript" src="/static/js/script1.js"></script>
    <script type="text/javascript" src="/static/js/script2.js"></script>
  </body>
</html>

app/templates/login.html
{% extends "layout.html" %} {% block content %}
<div class="body-main">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 mt-5">
      <div class="content-section-login tect-white">
        <h2 class="pb-2">Login</h2>

        <form method="POST" action="/loginvalidation">
          <label>Email</label><br />
          <input
            type="email"
            class="form-control"
            name="email"
            placeholder="email"
          /><br />
          <label>passcode</label><br />
          <input
            type="password"
            class="form-control"
            name="password"
            placeholder="password"
            <br
          /><br />
          <input
            type="submit"
            class="btn btn-block button-glass mb-2"
            value="Login"
          />
        </form>
        <div class="border-top pt-3">
          <small class="text-muted">
            Need An Account?
            <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
          </small>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

app/templates/map1.html
{% extends "layout.html" %} {% block content %}
<div class="container">
  <div class="row mt-5">
    <div class="col-md-10">
      <div id="map"></div>
    </div>
    <div class="col-md-2"></div>
    <form action="/map2" id="coords-form" method="POST">
      <label for="scoords"
        >Starting Coordinates
        <input type="text" name="scoords" id="" value="" />
      </label>
      <label for="ecoords"
        >Ending Coordinates
        <input type="text" name="ecoords" id="" value="" />
      </label>
      <div class="form-group btn btn-primary btn1">
        <button type="submit" id="submit">Start ride</button>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

app/templates/map2.html
{% extends "layout.html" %} {% block content %}

<div class="container">
  <div class="row mt-5">
    <div class="col-md-10">
      <div id="map2"></div>
    </div>
    <div class="col-md-2">
      <a class="btn btn-primary" href="{{ url_for('main.home') }}">end ride</a>
      <div class="card">
        <p>
          <h3>You are pooled with</h3>
          <br />
          <h4 style="font-weight: 600;color:beige;">{{user}}</h4>
          <br />
          <h3>Contact Your Poolmate</h3>
          <br />
          <h4 style="font-weight: 600;color:beige;">{{phn}}</h4>
        </p>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

app/templates/register.html
{% extends "layout.html" %} {% block content %}
<div class="body-main">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 mt-5">
      <div class="content-section-register">
        <h2 class="pb-2">Register</h2>
        <form method="POST" action="/add_user">
          <label>name</label><br />
          <input
            type="text"
            class="form-control"
            name="username"
            placeholder="name"
          /><br />
          <label>Email</label><br />
          <input
            type="email"
            class="form-control"
            name="useremail"
            placeholder="email"
          /><br />
          <label>passcode</label><br />
          <input
            type="password"
            class="form-control"
            name="userpassword"
            placeholder="password"
          /><br />
          <label>phone number</label><br />
          <input
            type="tel"
            class="form-control"
            name="userphone"
            placeholder="phone number"
          /><br /><br />

          <div class="form-group">
            <label for="gender">Select your gender:</label><br />
            <select name="gender" id="">
              <option value="">--choose an option--</option>
              <option value="M">Male</option>
              <option value="F">Female</option>
              <option value="N">Prefer Not to say</option>
            </select>
          </div>
          <br /><br />
          <label>Twitter Id</label><br />
          <input
            type="text"
            class="form-control"
            name="twitter_id"
            placeholder="twitter id"
          /><br /><br />

          <input
            type="submit"
            class="btn btn-block button-glass"
            value="Register"
          />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}